import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { SvgIconsModule } from '@ngneat/svg-icon';
import { NgxNationsIconModule } from '@ngx-nations/icon';
import {
  flagAg,
  flagAr,
  flagAw,
  flagBb,
  flagBo,
  flagBr,
  flagBs,
  flagBz,
  flagCa,
  flagCl,
  flagCo,
  flagCr,
  flagCu,
  flagDm,
  flagDo,
  flagEc,
  flagGd,
  flagGt,
  flagGy,
  flagHn,
  flagHt,
  flagJm,
  flagKn,
  flagLc,
  flagMx,
  flagNi,
  flagPa,
  flagPe,
  flagPr,
  flagPy,
  flagSr,
  flagSv,
  flagTt,
  flagUs,
  flagUy,
  flagVc,
  flagVe,
} from '@ngx-nations/icon/tw-icons';

import { AmericaComponent } from './america.component';
import { AmericaRoutingModule } from './america.routing';
import { CountryListModule } from '../country-list/country-list.module';

@NgModule({
  declarations: [AmericaComponent],
  imports: [
    CommonModule,
    AmericaRoutingModule,
    SvgIconsModule.forChild([
      flagAg,
      flagAr,
      flagAw,
      flagBb,
      flagBo,
      flagBr,
      flagBs,
      flagBz,
      flagCa,
      flagCl,
      flagCo,
      flagCr,
      flagCu,
      flagDm,
      flagDo,
      flagEc,
      flagGd,
      flagGt,
      flagGy,
      flagHn,
      flagHt,
      flagJm,
      flagKn,
      flagLc,
      flagMx,
      flagNi,
      flagPa,
      flagPe,
      flagPr,
      flagPy,
      flagSr,
      flagSv,
      flagTt,
      flagUs,
      flagUy,
      flagVc,
      flagVe,
    ]),
    CountryListModule,
    NgxNationsIconModule,
  ],
})
export class AmericaModule {}
