import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { SvgIconsModule } from '@ngneat/svg-icon';
import {
  ngxNationIconTwemojiAg,
  ngxNationIconTwemojiAr,
  ngxNationIconTwemojiAw,
  ngxNationIconTwemojiBb,
  ngxNationIconTwemojiBo,
  ngxNationIconTwemojiBr,
  ngxNationIconTwemojiBs,
  ngxNationIconTwemojiBz,
  ngxNationIconTwemojiCa,
  ngxNationIconTwemojiCl,
  ngxNationIconTwemojiCo,
  ngxNationIconTwemojiCr,
  ngxNationIconTwemojiCu,
  ngxNationIconTwemojiDm,
  ngxNationIconTwemojiDo,
  ngxNationIconTwemojiEc,
  ngxNationIconTwemojiGd,
  ngxNationIconTwemojiGt,
  ngxNationIconTwemojiGy,
  ngxNationIconTwemojiHn,
  ngxNationIconTwemojiHt,
  ngxNationIconTwemojiJm,
  ngxNationIconTwemojiKn,
  ngxNationIconTwemojiLc,
  ngxNationIconTwemojiMx,
  ngxNationIconTwemojiNi,
  ngxNationIconTwemojiPa,
  ngxNationIconTwemojiPe,
  ngxNationIconTwemojiPr,
  ngxNationIconTwemojiPy,
  ngxNationIconTwemojiSr,
  ngxNationIconTwemojiSv,
  ngxNationIconTwemojiTt,
  ngxNationIconTwemojiUs,
  ngxNationIconTwemojiUy,
  ngxNationIconTwemojiVc,
  ngxNationIconTwemojiVe,
  NgxNationsIconsTwemojiModule,
} from 'ngx-nations/twemoji-icons';

import { AmericaComponent } from './america.component';
import { AmericaRoutingModule } from './america.routing';

@NgModule({
  declarations: [AmericaComponent],
  imports: [
    CommonModule,
    AmericaRoutingModule,
    SvgIconsModule.forChild([
      ngxNationIconTwemojiAg,
      ngxNationIconTwemojiAr,
      ngxNationIconTwemojiAw,
      ngxNationIconTwemojiBb,
      ngxNationIconTwemojiBo,
      ngxNationIconTwemojiBr,
      ngxNationIconTwemojiBs,
      ngxNationIconTwemojiBz,
      ngxNationIconTwemojiCa,
      ngxNationIconTwemojiCl,
      ngxNationIconTwemojiCo,
      ngxNationIconTwemojiCr,
      ngxNationIconTwemojiCu,
      ngxNationIconTwemojiDm,
      ngxNationIconTwemojiDo,
      ngxNationIconTwemojiEc,
      ngxNationIconTwemojiGd,
      ngxNationIconTwemojiGt,
      ngxNationIconTwemojiGy,
      ngxNationIconTwemojiHn,
      ngxNationIconTwemojiHt,
      ngxNationIconTwemojiJm,
      ngxNationIconTwemojiKn,
      ngxNationIconTwemojiLc,
      ngxNationIconTwemojiMx,
      ngxNationIconTwemojiNi,
      ngxNationIconTwemojiPa,
      ngxNationIconTwemojiPe,
      ngxNationIconTwemojiPr,
      ngxNationIconTwemojiPy,
      ngxNationIconTwemojiSr,
      ngxNationIconTwemojiSv,
      ngxNationIconTwemojiTt,
      ngxNationIconTwemojiUs,
      ngxNationIconTwemojiUy,
      ngxNationIconTwemojiVc,
      ngxNationIconTwemojiVe,
    ]),
    NgxNationsIconsTwemojiModule,
  ],
})
export class AmericaModule {}
