/* 🤖 this file was generated by svg-to-ts*/
export const flagBq: {
  name: 'bq';
  data: string;
} = {
  name: 'bq',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 480"><path fill="#21468b" d="M0 0h640v480H0z"/><path fill="#fff" d="M0 0h640v320H0z"/><path fill="#ae1c28" d="M0 0h640v160H0z"/></svg>`
};
