import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { SvgIconsModule } from '@ngneat/svg-icon';
import { NgxNationsIconModule } from '@ngx-nations/icon';
import {
  flagAf,
  flagAm,
  flagAz,
  flagBh,
  flagBd,
  flagBt,
  flagBn,
  flagKh,
  flagCn,
  flagCc,
  flagGe,
  flagHk,
  flagIn,
  flagId,
  flagIr,
  flagIq,
  flagIl,
  flagJp,
  flagJo,
  flagKz,
  flagKw,
  flagKg,
  flagLa,
  flagLb,
  flagMo,
  flagMy,
  flagMv,
  flagMn,
  flagMm,
  flagNp,
  flagKp,
  flagOm,
  flagPk,
  flagPs,
  flagPh,
  flagQa,
  flagSa,
  flagSg,
  flagKr,
  flagLk,
  flagSy,
  flagTw,
  flagTj,
  flagTh,
  flagTr,
  flagTm,
  flagAe,
  flagUz,
  flagVn,
  flagYe,
} from '@ngx-nations/icon/tw-icons';

import { AsiaComponent } from './asia.component';
import { AsiaRoutingModule } from './asia.routing';
import { NationListModule } from '../../shared/list/list.module';

@NgModule({
  declarations: [AsiaComponent],
  imports: [
    CommonModule,
    AsiaRoutingModule,
    NationListModule,
    NgxNationsIconModule,
    SvgIconsModule.forChild([
      flagAf,
      flagAm,
      flagAz,
      flagBh,
      flagBd,
      flagBt,
      flagBn,
      flagKh,
      flagCn,
      flagCc,
      flagGe,
      flagHk,
      flagIn,
      flagId,
      flagIr,
      flagIq,
      flagIl,
      flagJp,
      flagJo,
      flagKz,
      flagKw,
      flagKg,
      flagLa,
      flagLb,
      flagMo,
      flagMy,
      flagMv,
      flagMn,
      flagMm,
      flagNp,
      flagKp,
      flagOm,
      flagPk,
      flagPs,
      flagPh,
      flagQa,
      flagSa,
      flagSg,
      flagKr,
      flagLk,
      flagSy,
      flagTw,
      flagTj,
      flagTh,
      flagTr,
      flagTm,
      flagAe,
      flagUz,
      flagVn,
      flagYe,
    ]),
  ],
})
export class AsiaModule {}
