import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  nationFlagAf,
  nationFlagAm,
  nationFlagAz,
  nationFlagBh,
  nationFlagBd,
  nationFlagBt,
  nationFlagBn,
  nationFlagKh,
  nationFlagCn,
  nationFlagCc,
  nationFlagGe,
  nationFlagHk,
  nationFlagIn,
  nationFlagId,
  nationFlagIr,
  nationFlagIq,
  nationFlagIl,
  nationFlagJp,
  nationFlagJo,
  nationFlagKz,
  nationFlagKw,
  nationFlagKg,
  nationFlagLa,
  nationFlagLb,
  nationFlagMo,
  nationFlagMy,
  nationFlagMv,
  nationFlagMn,
  nationFlagMm,
  nationFlagNp,
  nationFlagKp,
  nationFlagOm,
  nationFlagPk,
  nationFlagPs,
  nationFlagPh,
  nationFlagQa,
  nationFlagSa,
  nationFlagSg,
  nationFlagKr,
  nationFlagLk,
  nationFlagSy,
  nationFlagTw,
  nationFlagTj,
  nationFlagTh,
  nationFlagTr,
  nationFlagTm,
  nationFlagAe,
  nationFlagUz,
  nationFlagVn,
  nationFlagYe,
} from '@nation/tw-flags';
import { NationFlagAngularModule } from '@nation/ngx-flag';

import { AsiaComponent } from './asia.component';
import { AsiaRoutingModule } from './asia.routing';
import { NationListModule } from '../../shared/list/list.module';

@NgModule({
  declarations: [AsiaComponent],
  imports: [
    CommonModule,
    AsiaRoutingModule,
    NationListModule,
    NationFlagAngularModule.forChild([
      nationFlagAf,
      nationFlagAm,
      nationFlagAz,
      nationFlagBh,
      nationFlagBd,
      nationFlagBt,
      nationFlagBn,
      nationFlagKh,
      nationFlagCn,
      nationFlagCc,
      nationFlagGe,
      nationFlagHk,
      nationFlagIn,
      nationFlagId,
      nationFlagIr,
      nationFlagIq,
      nationFlagIl,
      nationFlagJp,
      nationFlagJo,
      nationFlagKz,
      nationFlagKw,
      nationFlagKg,
      nationFlagLa,
      nationFlagLb,
      nationFlagMo,
      nationFlagMy,
      nationFlagMv,
      nationFlagMn,
      nationFlagMm,
      nationFlagNp,
      nationFlagKp,
      nationFlagOm,
      nationFlagPk,
      nationFlagPs,
      nationFlagPh,
      nationFlagQa,
      nationFlagSa,
      nationFlagSg,
      nationFlagKr,
      nationFlagLk,
      nationFlagSy,
      nationFlagTw,
      nationFlagTj,
      nationFlagTh,
      nationFlagTr,
      nationFlagTm,
      nationFlagAe,
      nationFlagUz,
      nationFlagVn,
      nationFlagYe,
    ]),
  ],
})
export class AsiaModule {}
