import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { NationFlagAngularModule } from '@ngx-nations/nation-flag-angular';
import {
  flagAo,
  flagBf,
  flagBi,
  flagBj,
  flagBw,
  flagCd,
  flagCf,
  flagCg,
  flagCi,
  flagCm,
  flagCv,
  flagDj,
  flagDz,
  flagEg,
  flagEh,
  flagEr,
  flagEt,
  flagGa,
  flagGh,
  flagGm,
  flagGn,
  flagGq,
  flagGw,
  flagKe,
  flagKm,
  flagLr,
  flagLs,
  flagLy,
  flagMa,
  flagMg,
  flagMl,
  flagMr,
  flagMu,
  flagMw,
  flagMz,
  flagNa,
  flagNe,
  flagNg,
  flagRw,
  flagSc,
  flagSd,
  flagSl,
  flagSn,
  flagSo,
  flagSs,
  flagSt,
  flagSz,
  flagTd,
  flagTg,
  flagTn,
  flagTz,
  flagUg,
  flagZa,
  flagZm,
  flagZw,
} from '@ngx-nations/icon/tw-icons';

import { AfricaComponent } from './africa.component';
import { AfricaRoutingModule } from './africa.routing';
import { NationListModule } from '../../shared/list/list.module';

@NgModule({
  declarations: [AfricaComponent],
  imports: [
    CommonModule,
    AfricaRoutingModule,
    NationListModule,
    NationFlagAngularModule.forChild([
      flagAo,
      flagBf,
      flagBi,
      flagBj,
      flagBw,
      flagCd,
      flagCf,
      flagCg,
      flagCi,
      flagCm,
      flagCv,
      flagDj,
      flagDz,
      flagEg,
      flagEh,
      flagEr,
      flagEt,
      flagGa,
      flagGh,
      flagGm,
      flagGn,
      flagGq,
      flagGw,
      flagKe,
      flagKm,
      flagLr,
      flagLs,
      flagLy,
      flagMa,
      flagMg,
      flagMl,
      flagMr,
      flagMu,
      flagMw,
      flagMz,
      flagNa,
      flagNe,
      flagNg,
      flagRw,
      flagSc,
      flagSd,
      flagSl,
      flagSn,
      flagSo,
      flagSs,
      flagSt,
      flagSz,
      flagTd,
      flagTg,
      flagTn,
      flagTz,
      flagUg,
      flagZa,
      flagZm,
      flagZw,
    ]),
  ],
})
export class AfricaModule {}
