/* 🤖 this file was generated by svg-to-ts*/
import { flagAc } from './flag-AC.icon';
import { flagAd } from './flag-AD.icon';
import { flagAe } from './flag-AE.icon';
import { flagAf } from './flag-AF.icon';
import { flagAg } from './flag-AG.icon';
import { flagAi } from './flag-AI.icon';
import { flagAl } from './flag-AL.icon';
import { flagAm } from './flag-AM.icon';
import { flagAo } from './flag-AO.icon';
import { flagAq } from './flag-AQ.icon';
import { flagAr } from './flag-AR.icon';
import { flagAs } from './flag-AS.icon';
import { flagAt } from './flag-AT.icon';
import { flagAu } from './flag-AU.icon';
import { flagAw } from './flag-AW.icon';
import { flagAx } from './flag-AX.icon';
import { flagAz } from './flag-AZ.icon';
import { flagBa } from './flag-BA.icon';
import { flagBb } from './flag-BB.icon';
import { flagBd } from './flag-BD.icon';
import { flagBe } from './flag-BE.icon';
import { flagBf } from './flag-BF.icon';
import { flagBg } from './flag-BG.icon';
import { flagBh } from './flag-BH.icon';
import { flagBi } from './flag-BI.icon';
import { flagBj } from './flag-BJ.icon';
import { flagBl } from './flag-BL.icon';
import { flagBm } from './flag-BM.icon';
import { flagBn } from './flag-BN.icon';
import { flagBo } from './flag-BO.icon';
import { flagBq } from './flag-BQ.icon';
import { flagBr } from './flag-BR.icon';
import { flagBs } from './flag-BS.icon';
import { flagBt } from './flag-BT.icon';
import { flagBv } from './flag-BV.icon';
import { flagBw } from './flag-BW.icon';
import { flagBy } from './flag-BY.icon';
import { flagBz } from './flag-BZ.icon';
import { flagCa } from './flag-CA.icon';
import { flagCc } from './flag-CC.icon';
import { flagCd } from './flag-CD.icon';
import { flagCf } from './flag-CF.icon';
import { flagCg } from './flag-CG.icon';
import { flagCh } from './flag-CH.icon';
import { flagCi } from './flag-CI.icon';
import { flagCk } from './flag-CK.icon';
import { flagCl } from './flag-CL.icon';
import { flagCm } from './flag-CM.icon';
import { flagCn } from './flag-CN.icon';
import { flagCo } from './flag-CO.icon';
import { flagCp } from './flag-CP.icon';
import { flagCr } from './flag-CR.icon';
import { flagCu } from './flag-CU.icon';
import { flagCv } from './flag-CV.icon';
import { flagCw } from './flag-CW.icon';
import { flagCx } from './flag-CX.icon';
import { flagCy } from './flag-CY.icon';
import { flagCz } from './flag-CZ.icon';
import { flagDe } from './flag-DE.icon';
import { flagDg } from './flag-DG.icon';
import { flagDj } from './flag-DJ.icon';
import { flagDk } from './flag-DK.icon';
import { flagDm } from './flag-DM.icon';
import { flagDo } from './flag-DO.icon';
import { flagDz } from './flag-DZ.icon';
import { flagEa } from './flag-EA.icon';
import { flagEc } from './flag-EC.icon';
import { flagEe } from './flag-EE.icon';
import { flagEg } from './flag-EG.icon';
import { flagEh } from './flag-EH.icon';
import { flagEr } from './flag-ER.icon';
import { flagEs } from './flag-ES.icon';
import { flagEt } from './flag-ET.icon';
import { flagEu } from './flag-EU.icon';
import { flagFi } from './flag-FI.icon';
import { flagFj } from './flag-FJ.icon';
import { flagFk } from './flag-FK.icon';
import { flagFm } from './flag-FM.icon';
import { flagFo } from './flag-FO.icon';
import { flagFr } from './flag-FR.icon';
import { flagGa } from './flag-GA.icon';
import { flagGb } from './flag-GB.icon';
import { flagGd } from './flag-GD.icon';
import { flagGe } from './flag-GE.icon';
import { flagGf } from './flag-GF.icon';
import { flagGg } from './flag-GG.icon';
import { flagGh } from './flag-GH.icon';
import { flagGi } from './flag-GI.icon';
import { flagGl } from './flag-GL.icon';
import { flagGm } from './flag-GM.icon';
import { flagGn } from './flag-GN.icon';
import { flagGp } from './flag-GP.icon';
import { flagGq } from './flag-GQ.icon';
import { flagGr } from './flag-GR.icon';
import { flagGs } from './flag-GS.icon';
import { flagGt } from './flag-GT.icon';
import { flagGu } from './flag-GU.icon';
import { flagGw } from './flag-GW.icon';
import { flagGy } from './flag-GY.icon';
import { flagHk } from './flag-HK.icon';
import { flagHm } from './flag-HM.icon';
import { flagHn } from './flag-HN.icon';
import { flagHr } from './flag-HR.icon';
import { flagHt } from './flag-HT.icon';
import { flagHu } from './flag-HU.icon';
import { flagIc } from './flag-IC.icon';
import { flagId } from './flag-ID.icon';
import { flagIe } from './flag-IE.icon';
import { flagIl } from './flag-IL.icon';
import { flagIm } from './flag-IM.icon';
import { flagIn } from './flag-IN.icon';
import { flagIo } from './flag-IO.icon';
import { flagIq } from './flag-IQ.icon';
import { flagIr } from './flag-IR.icon';
import { flagIs } from './flag-IS.icon';
import { flagIt } from './flag-IT.icon';
import { flagJe } from './flag-JE.icon';
import { flagJm } from './flag-JM.icon';
import { flagJo } from './flag-JO.icon';
import { flagJp } from './flag-JP.icon';
import { flagKe } from './flag-KE.icon';
import { flagKg } from './flag-KG.icon';
import { flagKh } from './flag-KH.icon';
import { flagKi } from './flag-KI.icon';
import { flagKm } from './flag-KM.icon';
import { flagKn } from './flag-KN.icon';
import { flagKp } from './flag-KP.icon';
import { flagKr } from './flag-KR.icon';
import { flagKw } from './flag-KW.icon';
import { flagKy } from './flag-KY.icon';
import { flagKz } from './flag-KZ.icon';
import { flagLa } from './flag-LA.icon';
import { flagLb } from './flag-LB.icon';
import { flagLc } from './flag-LC.icon';
import { flagLi } from './flag-LI.icon';
import { flagLk } from './flag-LK.icon';
import { flagLr } from './flag-LR.icon';
import { flagLs } from './flag-LS.icon';
import { flagLt } from './flag-LT.icon';
import { flagLu } from './flag-LU.icon';
import { flagLv } from './flag-LV.icon';
import { flagLy } from './flag-LY.icon';
import { flagMa } from './flag-MA.icon';
import { flagMc } from './flag-MC.icon';
import { flagMd } from './flag-MD.icon';
import { flagMe } from './flag-ME.icon';
import { flagMf } from './flag-MF.icon';
import { flagMg } from './flag-MG.icon';
import { flagMh } from './flag-MH.icon';
import { flagMk } from './flag-MK.icon';
import { flagMl } from './flag-ML.icon';
import { flagMm } from './flag-MM.icon';
import { flagMn } from './flag-MN.icon';
import { flagMo } from './flag-MO.icon';
import { flagMp } from './flag-MP.icon';
import { flagMq } from './flag-MQ.icon';
import { flagMr } from './flag-MR.icon';
import { flagMs } from './flag-MS.icon';
import { flagMt } from './flag-MT.icon';
import { flagMu } from './flag-MU.icon';
import { flagMv } from './flag-MV.icon';
import { flagMw } from './flag-MW.icon';
import { flagMx } from './flag-MX.icon';
import { flagMy } from './flag-MY.icon';
import { flagMz } from './flag-MZ.icon';
import { flagNa } from './flag-NA.icon';
import { flagNc } from './flag-NC.icon';
import { flagNe } from './flag-NE.icon';
import { flagNf } from './flag-NF.icon';
import { flagNg } from './flag-NG.icon';
import { flagNi } from './flag-NI.icon';
import { flagNl } from './flag-NL.icon';
import { flagNo } from './flag-NO.icon';
import { flagNp } from './flag-NP.icon';
import { flagNr } from './flag-NR.icon';
import { flagNu } from './flag-NU.icon';
import { flagNz } from './flag-NZ.icon';
import { flagOm } from './flag-OM.icon';
import { flagPa } from './flag-PA.icon';
import { flagPe } from './flag-PE.icon';
import { flagPf } from './flag-PF.icon';
import { flagPg } from './flag-PG.icon';
import { flagPh } from './flag-PH.icon';
import { flagPk } from './flag-PK.icon';
import { flagPl } from './flag-PL.icon';
import { flagPm } from './flag-PM.icon';
import { flagPn } from './flag-PN.icon';
import { flagPr } from './flag-PR.icon';
import { flagPs } from './flag-PS.icon';
import { flagPt } from './flag-PT.icon';
import { flagPw } from './flag-PW.icon';
import { flagPy } from './flag-PY.icon';
import { flagQa } from './flag-QA.icon';
import { flagRe } from './flag-RE.icon';
import { flagRo } from './flag-RO.icon';
import { flagRs } from './flag-RS.icon';
import { flagRu } from './flag-RU.icon';
import { flagRw } from './flag-RW.icon';
import { flagSa } from './flag-SA.icon';
import { flagSb } from './flag-SB.icon';
import { flagSc } from './flag-SC.icon';
import { flagSd } from './flag-SD.icon';
import { flagSe } from './flag-SE.icon';
import { flagSg } from './flag-SG.icon';
import { flagSh } from './flag-SH.icon';
import { flagSi } from './flag-SI.icon';
import { flagSj } from './flag-SJ.icon';
import { flagSk } from './flag-SK.icon';
import { flagSl } from './flag-SL.icon';
import { flagSm } from './flag-SM.icon';
import { flagSn } from './flag-SN.icon';
import { flagSo } from './flag-SO.icon';
import { flagSr } from './flag-SR.icon';
import { flagSs } from './flag-SS.icon';
import { flagSt } from './flag-ST.icon';
import { flagSv } from './flag-SV.icon';
import { flagSx } from './flag-SX.icon';
import { flagSy } from './flag-SY.icon';
import { flagSz } from './flag-SZ.icon';
import { flagTa } from './flag-TA.icon';
import { flagTc } from './flag-TC.icon';
import { flagTd } from './flag-TD.icon';
import { flagTf } from './flag-TF.icon';
import { flagTg } from './flag-TG.icon';
import { flagTh } from './flag-TH.icon';
import { flagTj } from './flag-TJ.icon';
import { flagTk } from './flag-TK.icon';
import { flagTl } from './flag-TL.icon';
import { flagTm } from './flag-TM.icon';
import { flagTn } from './flag-TN.icon';
import { flagTo } from './flag-TO.icon';
import { flagTr } from './flag-TR.icon';
import { flagTt } from './flag-TT.icon';
import { flagTv } from './flag-TV.icon';
import { flagTw } from './flag-TW.icon';
import { flagTz } from './flag-TZ.icon';
import { flagUa } from './flag-UA.icon';
import { flagUg } from './flag-UG.icon';
import { flagUm } from './flag-UM.icon';
import { flagUn } from './flag-UN.icon';
import { flagUs } from './flag-US.icon';
import { flagUy } from './flag-UY.icon';
import { flagUz } from './flag-UZ.icon';
import { flagVa } from './flag-VA.icon';
import { flagVc } from './flag-VC.icon';
import { flagVe } from './flag-VE.icon';
import { flagVg } from './flag-VG.icon';
import { flagVi } from './flag-VI.icon';
import { flagVn } from './flag-VN.icon';
import { flagVu } from './flag-VU.icon';
import { flagWf } from './flag-WF.icon';
import { flagWs } from './flag-WS.icon';
import { flagXk } from './flag-XK.icon';
import { flagYe } from './flag-YE.icon';
import { flagYt } from './flag-YT.icon';
import { flagZa } from './flag-ZA.icon';
import { flagZm } from './flag-ZM.icon';
import { flagZw } from './flag-ZW.icon';
export const completeIconSet = [
  flagAc,
  flagAd,
  flagAe,
  flagAf,
  flagAg,
  flagAi,
  flagAl,
  flagAm,
  flagAo,
  flagAq,
  flagAr,
  flagAs,
  flagAt,
  flagAu,
  flagAw,
  flagAx,
  flagAz,
  flagBa,
  flagBb,
  flagBd,
  flagBe,
  flagBf,
  flagBg,
  flagBh,
  flagBi,
  flagBj,
  flagBl,
  flagBm,
  flagBn,
  flagBo,
  flagBq,
  flagBr,
  flagBs,
  flagBt,
  flagBv,
  flagBw,
  flagBy,
  flagBz,
  flagCa,
  flagCc,
  flagCd,
  flagCf,
  flagCg,
  flagCh,
  flagCi,
  flagCk,
  flagCl,
  flagCm,
  flagCn,
  flagCo,
  flagCp,
  flagCr,
  flagCu,
  flagCv,
  flagCw,
  flagCx,
  flagCy,
  flagCz,
  flagDe,
  flagDg,
  flagDj,
  flagDk,
  flagDm,
  flagDo,
  flagDz,
  flagEa,
  flagEc,
  flagEe,
  flagEg,
  flagEh,
  flagEr,
  flagEs,
  flagEt,
  flagEu,
  flagFi,
  flagFj,
  flagFk,
  flagFm,
  flagFo,
  flagFr,
  flagGa,
  flagGb,
  flagGd,
  flagGe,
  flagGf,
  flagGg,
  flagGh,
  flagGi,
  flagGl,
  flagGm,
  flagGn,
  flagGp,
  flagGq,
  flagGr,
  flagGs,
  flagGt,
  flagGu,
  flagGw,
  flagGy,
  flagHk,
  flagHm,
  flagHn,
  flagHr,
  flagHt,
  flagHu,
  flagIc,
  flagId,
  flagIe,
  flagIl,
  flagIm,
  flagIn,
  flagIo,
  flagIq,
  flagIr,
  flagIs,
  flagIt,
  flagJe,
  flagJm,
  flagJo,
  flagJp,
  flagKe,
  flagKg,
  flagKh,
  flagKi,
  flagKm,
  flagKn,
  flagKp,
  flagKr,
  flagKw,
  flagKy,
  flagKz,
  flagLa,
  flagLb,
  flagLc,
  flagLi,
  flagLk,
  flagLr,
  flagLs,
  flagLt,
  flagLu,
  flagLv,
  flagLy,
  flagMa,
  flagMc,
  flagMd,
  flagMe,
  flagMf,
  flagMg,
  flagMh,
  flagMk,
  flagMl,
  flagMm,
  flagMn,
  flagMo,
  flagMp,
  flagMq,
  flagMr,
  flagMs,
  flagMt,
  flagMu,
  flagMv,
  flagMw,
  flagMx,
  flagMy,
  flagMz,
  flagNa,
  flagNc,
  flagNe,
  flagNf,
  flagNg,
  flagNi,
  flagNl,
  flagNo,
  flagNp,
  flagNr,
  flagNu,
  flagNz,
  flagOm,
  flagPa,
  flagPe,
  flagPf,
  flagPg,
  flagPh,
  flagPk,
  flagPl,
  flagPm,
  flagPn,
  flagPr,
  flagPs,
  flagPt,
  flagPw,
  flagPy,
  flagQa,
  flagRe,
  flagRo,
  flagRs,
  flagRu,
  flagRw,
  flagSa,
  flagSb,
  flagSc,
  flagSd,
  flagSe,
  flagSg,
  flagSh,
  flagSi,
  flagSj,
  flagSk,
  flagSl,
  flagSm,
  flagSn,
  flagSo,
  flagSr,
  flagSs,
  flagSt,
  flagSv,
  flagSx,
  flagSy,
  flagSz,
  flagTa,
  flagTc,
  flagTd,
  flagTf,
  flagTg,
  flagTh,
  flagTj,
  flagTk,
  flagTl,
  flagTm,
  flagTn,
  flagTo,
  flagTr,
  flagTt,
  flagTv,
  flagTw,
  flagTz,
  flagUa,
  flagUg,
  flagUm,
  flagUn,
  flagUs,
  flagUy,
  flagUz,
  flagVa,
  flagVc,
  flagVe,
  flagVg,
  flagVi,
  flagVn,
  flagVu,
  flagWf,
  flagWs,
  flagXk,
  flagYe,
  flagYt,
  flagZa,
  flagZm,
  flagZw
];
