/* 🤖 this file was generated by svg-to-ts*/
import { nationFlagAc } from './nationFlag-AC.icon';
import { nationFlagAd } from './nationFlag-AD.icon';
import { nationFlagAe } from './nationFlag-AE.icon';
import { nationFlagAf } from './nationFlag-AF.icon';
import { nationFlagAg } from './nationFlag-AG.icon';
import { nationFlagAi } from './nationFlag-AI.icon';
import { nationFlagAl } from './nationFlag-AL.icon';
import { nationFlagAm } from './nationFlag-AM.icon';
import { nationFlagAo } from './nationFlag-AO.icon';
import { nationFlagAq } from './nationFlag-AQ.icon';
import { nationFlagAr } from './nationFlag-AR.icon';
import { nationFlagAs } from './nationFlag-AS.icon';
import { nationFlagAt } from './nationFlag-AT.icon';
import { nationFlagAu } from './nationFlag-AU.icon';
import { nationFlagAw } from './nationFlag-AW.icon';
import { nationFlagAx } from './nationFlag-AX.icon';
import { nationFlagAz } from './nationFlag-AZ.icon';
import { nationFlagBa } from './nationFlag-BA.icon';
import { nationFlagBb } from './nationFlag-BB.icon';
import { nationFlagBd } from './nationFlag-BD.icon';
import { nationFlagBe } from './nationFlag-BE.icon';
import { nationFlagBf } from './nationFlag-BF.icon';
import { nationFlagBg } from './nationFlag-BG.icon';
import { nationFlagBh } from './nationFlag-BH.icon';
import { nationFlagBi } from './nationFlag-BI.icon';
import { nationFlagBj } from './nationFlag-BJ.icon';
import { nationFlagBl } from './nationFlag-BL.icon';
import { nationFlagBm } from './nationFlag-BM.icon';
import { nationFlagBn } from './nationFlag-BN.icon';
import { nationFlagBo } from './nationFlag-BO.icon';
import { nationFlagBq } from './nationFlag-BQ.icon';
import { nationFlagBr } from './nationFlag-BR.icon';
import { nationFlagBs } from './nationFlag-BS.icon';
import { nationFlagBt } from './nationFlag-BT.icon';
import { nationFlagBv } from './nationFlag-BV.icon';
import { nationFlagBw } from './nationFlag-BW.icon';
import { nationFlagBy } from './nationFlag-BY.icon';
import { nationFlagBz } from './nationFlag-BZ.icon';
import { nationFlagCa } from './nationFlag-CA.icon';
import { nationFlagCc } from './nationFlag-CC.icon';
import { nationFlagCd } from './nationFlag-CD.icon';
import { nationFlagCf } from './nationFlag-CF.icon';
import { nationFlagCg } from './nationFlag-CG.icon';
import { nationFlagCh } from './nationFlag-CH.icon';
import { nationFlagCi } from './nationFlag-CI.icon';
import { nationFlagCk } from './nationFlag-CK.icon';
import { nationFlagCl } from './nationFlag-CL.icon';
import { nationFlagCm } from './nationFlag-CM.icon';
import { nationFlagCn } from './nationFlag-CN.icon';
import { nationFlagCo } from './nationFlag-CO.icon';
import { nationFlagCp } from './nationFlag-CP.icon';
import { nationFlagCr } from './nationFlag-CR.icon';
import { nationFlagCu } from './nationFlag-CU.icon';
import { nationFlagCv } from './nationFlag-CV.icon';
import { nationFlagCw } from './nationFlag-CW.icon';
import { nationFlagCx } from './nationFlag-CX.icon';
import { nationFlagCy } from './nationFlag-CY.icon';
import { nationFlagCz } from './nationFlag-CZ.icon';
import { nationFlagDe } from './nationFlag-DE.icon';
import { nationFlagDg } from './nationFlag-DG.icon';
import { nationFlagDj } from './nationFlag-DJ.icon';
import { nationFlagDk } from './nationFlag-DK.icon';
import { nationFlagDm } from './nationFlag-DM.icon';
import { nationFlagDo } from './nationFlag-DO.icon';
import { nationFlagDz } from './nationFlag-DZ.icon';
import { nationFlagEa } from './nationFlag-EA.icon';
import { nationFlagEc } from './nationFlag-EC.icon';
import { nationFlagEe } from './nationFlag-EE.icon';
import { nationFlagEg } from './nationFlag-EG.icon';
import { nationFlagEh } from './nationFlag-EH.icon';
import { nationFlagEr } from './nationFlag-ER.icon';
import { nationFlagEs } from './nationFlag-ES.icon';
import { nationFlagEt } from './nationFlag-ET.icon';
import { nationFlagEu } from './nationFlag-EU.icon';
import { nationFlagFi } from './nationFlag-FI.icon';
import { nationFlagFj } from './nationFlag-FJ.icon';
import { nationFlagFk } from './nationFlag-FK.icon';
import { nationFlagFm } from './nationFlag-FM.icon';
import { nationFlagFo } from './nationFlag-FO.icon';
import { nationFlagFr } from './nationFlag-FR.icon';
import { nationFlagGa } from './nationFlag-GA.icon';
import { nationFlagGb } from './nationFlag-GB.icon';
import { nationFlagGd } from './nationFlag-GD.icon';
import { nationFlagGe } from './nationFlag-GE.icon';
import { nationFlagGf } from './nationFlag-GF.icon';
import { nationFlagGg } from './nationFlag-GG.icon';
import { nationFlagGh } from './nationFlag-GH.icon';
import { nationFlagGi } from './nationFlag-GI.icon';
import { nationFlagGl } from './nationFlag-GL.icon';
import { nationFlagGm } from './nationFlag-GM.icon';
import { nationFlagGn } from './nationFlag-GN.icon';
import { nationFlagGp } from './nationFlag-GP.icon';
import { nationFlagGq } from './nationFlag-GQ.icon';
import { nationFlagGr } from './nationFlag-GR.icon';
import { nationFlagGs } from './nationFlag-GS.icon';
import { nationFlagGt } from './nationFlag-GT.icon';
import { nationFlagGu } from './nationFlag-GU.icon';
import { nationFlagGw } from './nationFlag-GW.icon';
import { nationFlagGy } from './nationFlag-GY.icon';
import { nationFlagHk } from './nationFlag-HK.icon';
import { nationFlagHm } from './nationFlag-HM.icon';
import { nationFlagHn } from './nationFlag-HN.icon';
import { nationFlagHr } from './nationFlag-HR.icon';
import { nationFlagHt } from './nationFlag-HT.icon';
import { nationFlagHu } from './nationFlag-HU.icon';
import { nationFlagIc } from './nationFlag-IC.icon';
import { nationFlagId } from './nationFlag-ID.icon';
import { nationFlagIe } from './nationFlag-IE.icon';
import { nationFlagIl } from './nationFlag-IL.icon';
import { nationFlagIm } from './nationFlag-IM.icon';
import { nationFlagIn } from './nationFlag-IN.icon';
import { nationFlagIo } from './nationFlag-IO.icon';
import { nationFlagIq } from './nationFlag-IQ.icon';
import { nationFlagIr } from './nationFlag-IR.icon';
import { nationFlagIs } from './nationFlag-IS.icon';
import { nationFlagIt } from './nationFlag-IT.icon';
import { nationFlagJe } from './nationFlag-JE.icon';
import { nationFlagJm } from './nationFlag-JM.icon';
import { nationFlagJo } from './nationFlag-JO.icon';
import { nationFlagJp } from './nationFlag-JP.icon';
import { nationFlagKe } from './nationFlag-KE.icon';
import { nationFlagKg } from './nationFlag-KG.icon';
import { nationFlagKh } from './nationFlag-KH.icon';
import { nationFlagKi } from './nationFlag-KI.icon';
import { nationFlagKm } from './nationFlag-KM.icon';
import { nationFlagKn } from './nationFlag-KN.icon';
import { nationFlagKp } from './nationFlag-KP.icon';
import { nationFlagKr } from './nationFlag-KR.icon';
import { nationFlagKw } from './nationFlag-KW.icon';
import { nationFlagKy } from './nationFlag-KY.icon';
import { nationFlagKz } from './nationFlag-KZ.icon';
import { nationFlagLa } from './nationFlag-LA.icon';
import { nationFlagLb } from './nationFlag-LB.icon';
import { nationFlagLc } from './nationFlag-LC.icon';
import { nationFlagLi } from './nationFlag-LI.icon';
import { nationFlagLk } from './nationFlag-LK.icon';
import { nationFlagLr } from './nationFlag-LR.icon';
import { nationFlagLs } from './nationFlag-LS.icon';
import { nationFlagLt } from './nationFlag-LT.icon';
import { nationFlagLu } from './nationFlag-LU.icon';
import { nationFlagLv } from './nationFlag-LV.icon';
import { nationFlagLy } from './nationFlag-LY.icon';
import { nationFlagMa } from './nationFlag-MA.icon';
import { nationFlagMc } from './nationFlag-MC.icon';
import { nationFlagMd } from './nationFlag-MD.icon';
import { nationFlagMe } from './nationFlag-ME.icon';
import { nationFlagMf } from './nationFlag-MF.icon';
import { nationFlagMg } from './nationFlag-MG.icon';
import { nationFlagMh } from './nationFlag-MH.icon';
import { nationFlagMk } from './nationFlag-MK.icon';
import { nationFlagMl } from './nationFlag-ML.icon';
import { nationFlagMm } from './nationFlag-MM.icon';
import { nationFlagMn } from './nationFlag-MN.icon';
import { nationFlagMo } from './nationFlag-MO.icon';
import { nationFlagMp } from './nationFlag-MP.icon';
import { nationFlagMq } from './nationFlag-MQ.icon';
import { nationFlagMr } from './nationFlag-MR.icon';
import { nationFlagMs } from './nationFlag-MS.icon';
import { nationFlagMt } from './nationFlag-MT.icon';
import { nationFlagMu } from './nationFlag-MU.icon';
import { nationFlagMv } from './nationFlag-MV.icon';
import { nationFlagMw } from './nationFlag-MW.icon';
import { nationFlagMx } from './nationFlag-MX.icon';
import { nationFlagMy } from './nationFlag-MY.icon';
import { nationFlagMz } from './nationFlag-MZ.icon';
import { nationFlagNa } from './nationFlag-NA.icon';
import { nationFlagNc } from './nationFlag-NC.icon';
import { nationFlagNe } from './nationFlag-NE.icon';
import { nationFlagNf } from './nationFlag-NF.icon';
import { nationFlagNg } from './nationFlag-NG.icon';
import { nationFlagNi } from './nationFlag-NI.icon';
import { nationFlagNl } from './nationFlag-NL.icon';
import { nationFlagNo } from './nationFlag-NO.icon';
import { nationFlagNp } from './nationFlag-NP.icon';
import { nationFlagNr } from './nationFlag-NR.icon';
import { nationFlagNu } from './nationFlag-NU.icon';
import { nationFlagNz } from './nationFlag-NZ.icon';
import { nationFlagOm } from './nationFlag-OM.icon';
import { nationFlagPa } from './nationFlag-PA.icon';
import { nationFlagPe } from './nationFlag-PE.icon';
import { nationFlagPf } from './nationFlag-PF.icon';
import { nationFlagPg } from './nationFlag-PG.icon';
import { nationFlagPh } from './nationFlag-PH.icon';
import { nationFlagPk } from './nationFlag-PK.icon';
import { nationFlagPl } from './nationFlag-PL.icon';
import { nationFlagPm } from './nationFlag-PM.icon';
import { nationFlagPn } from './nationFlag-PN.icon';
import { nationFlagPr } from './nationFlag-PR.icon';
import { nationFlagPs } from './nationFlag-PS.icon';
import { nationFlagPt } from './nationFlag-PT.icon';
import { nationFlagPw } from './nationFlag-PW.icon';
import { nationFlagPy } from './nationFlag-PY.icon';
import { nationFlagQa } from './nationFlag-QA.icon';
import { nationFlagRe } from './nationFlag-RE.icon';
import { nationFlagRo } from './nationFlag-RO.icon';
import { nationFlagRs } from './nationFlag-RS.icon';
import { nationFlagRu } from './nationFlag-RU.icon';
import { nationFlagRw } from './nationFlag-RW.icon';
import { nationFlagSa } from './nationFlag-SA.icon';
import { nationFlagSb } from './nationFlag-SB.icon';
import { nationFlagSc } from './nationFlag-SC.icon';
import { nationFlagSd } from './nationFlag-SD.icon';
import { nationFlagSe } from './nationFlag-SE.icon';
import { nationFlagSg } from './nationFlag-SG.icon';
import { nationFlagSh } from './nationFlag-SH.icon';
import { nationFlagSi } from './nationFlag-SI.icon';
import { nationFlagSj } from './nationFlag-SJ.icon';
import { nationFlagSk } from './nationFlag-SK.icon';
import { nationFlagSl } from './nationFlag-SL.icon';
import { nationFlagSm } from './nationFlag-SM.icon';
import { nationFlagSn } from './nationFlag-SN.icon';
import { nationFlagSo } from './nationFlag-SO.icon';
import { nationFlagSr } from './nationFlag-SR.icon';
import { nationFlagSs } from './nationFlag-SS.icon';
import { nationFlagSt } from './nationFlag-ST.icon';
import { nationFlagSv } from './nationFlag-SV.icon';
import { nationFlagSx } from './nationFlag-SX.icon';
import { nationFlagSy } from './nationFlag-SY.icon';
import { nationFlagSz } from './nationFlag-SZ.icon';
import { nationFlagTa } from './nationFlag-TA.icon';
import { nationFlagTc } from './nationFlag-TC.icon';
import { nationFlagTd } from './nationFlag-TD.icon';
import { nationFlagTf } from './nationFlag-TF.icon';
import { nationFlagTg } from './nationFlag-TG.icon';
import { nationFlagTh } from './nationFlag-TH.icon';
import { nationFlagTj } from './nationFlag-TJ.icon';
import { nationFlagTk } from './nationFlag-TK.icon';
import { nationFlagTl } from './nationFlag-TL.icon';
import { nationFlagTm } from './nationFlag-TM.icon';
import { nationFlagTn } from './nationFlag-TN.icon';
import { nationFlagTo } from './nationFlag-TO.icon';
import { nationFlagTr } from './nationFlag-TR.icon';
import { nationFlagTt } from './nationFlag-TT.icon';
import { nationFlagTv } from './nationFlag-TV.icon';
import { nationFlagTw } from './nationFlag-TW.icon';
import { nationFlagTz } from './nationFlag-TZ.icon';
import { nationFlagUa } from './nationFlag-UA.icon';
import { nationFlagUg } from './nationFlag-UG.icon';
import { nationFlagUm } from './nationFlag-UM.icon';
import { nationFlagUn } from './nationFlag-UN.icon';
import { nationFlagUs } from './nationFlag-US.icon';
import { nationFlagUy } from './nationFlag-UY.icon';
import { nationFlagUz } from './nationFlag-UZ.icon';
import { nationFlagVa } from './nationFlag-VA.icon';
import { nationFlagVc } from './nationFlag-VC.icon';
import { nationFlagVe } from './nationFlag-VE.icon';
import { nationFlagVg } from './nationFlag-VG.icon';
import { nationFlagVi } from './nationFlag-VI.icon';
import { nationFlagVn } from './nationFlag-VN.icon';
import { nationFlagVu } from './nationFlag-VU.icon';
import { nationFlagWf } from './nationFlag-WF.icon';
import { nationFlagWs } from './nationFlag-WS.icon';
import { nationFlagXk } from './nationFlag-XK.icon';
import { nationFlagYe } from './nationFlag-YE.icon';
import { nationFlagYt } from './nationFlag-YT.icon';
import { nationFlagZa } from './nationFlag-ZA.icon';
import { nationFlagZm } from './nationFlag-ZM.icon';
import { nationFlagZw } from './nationFlag-ZW.icon';
export const completeIconSet = [
  nationFlagAc,
  nationFlagAd,
  nationFlagAe,
  nationFlagAf,
  nationFlagAg,
  nationFlagAi,
  nationFlagAl,
  nationFlagAm,
  nationFlagAo,
  nationFlagAq,
  nationFlagAr,
  nationFlagAs,
  nationFlagAt,
  nationFlagAu,
  nationFlagAw,
  nationFlagAx,
  nationFlagAz,
  nationFlagBa,
  nationFlagBb,
  nationFlagBd,
  nationFlagBe,
  nationFlagBf,
  nationFlagBg,
  nationFlagBh,
  nationFlagBi,
  nationFlagBj,
  nationFlagBl,
  nationFlagBm,
  nationFlagBn,
  nationFlagBo,
  nationFlagBq,
  nationFlagBr,
  nationFlagBs,
  nationFlagBt,
  nationFlagBv,
  nationFlagBw,
  nationFlagBy,
  nationFlagBz,
  nationFlagCa,
  nationFlagCc,
  nationFlagCd,
  nationFlagCf,
  nationFlagCg,
  nationFlagCh,
  nationFlagCi,
  nationFlagCk,
  nationFlagCl,
  nationFlagCm,
  nationFlagCn,
  nationFlagCo,
  nationFlagCp,
  nationFlagCr,
  nationFlagCu,
  nationFlagCv,
  nationFlagCw,
  nationFlagCx,
  nationFlagCy,
  nationFlagCz,
  nationFlagDe,
  nationFlagDg,
  nationFlagDj,
  nationFlagDk,
  nationFlagDm,
  nationFlagDo,
  nationFlagDz,
  nationFlagEa,
  nationFlagEc,
  nationFlagEe,
  nationFlagEg,
  nationFlagEh,
  nationFlagEr,
  nationFlagEs,
  nationFlagEt,
  nationFlagEu,
  nationFlagFi,
  nationFlagFj,
  nationFlagFk,
  nationFlagFm,
  nationFlagFo,
  nationFlagFr,
  nationFlagGa,
  nationFlagGb,
  nationFlagGd,
  nationFlagGe,
  nationFlagGf,
  nationFlagGg,
  nationFlagGh,
  nationFlagGi,
  nationFlagGl,
  nationFlagGm,
  nationFlagGn,
  nationFlagGp,
  nationFlagGq,
  nationFlagGr,
  nationFlagGs,
  nationFlagGt,
  nationFlagGu,
  nationFlagGw,
  nationFlagGy,
  nationFlagHk,
  nationFlagHm,
  nationFlagHn,
  nationFlagHr,
  nationFlagHt,
  nationFlagHu,
  nationFlagIc,
  nationFlagId,
  nationFlagIe,
  nationFlagIl,
  nationFlagIm,
  nationFlagIn,
  nationFlagIo,
  nationFlagIq,
  nationFlagIr,
  nationFlagIs,
  nationFlagIt,
  nationFlagJe,
  nationFlagJm,
  nationFlagJo,
  nationFlagJp,
  nationFlagKe,
  nationFlagKg,
  nationFlagKh,
  nationFlagKi,
  nationFlagKm,
  nationFlagKn,
  nationFlagKp,
  nationFlagKr,
  nationFlagKw,
  nationFlagKy,
  nationFlagKz,
  nationFlagLa,
  nationFlagLb,
  nationFlagLc,
  nationFlagLi,
  nationFlagLk,
  nationFlagLr,
  nationFlagLs,
  nationFlagLt,
  nationFlagLu,
  nationFlagLv,
  nationFlagLy,
  nationFlagMa,
  nationFlagMc,
  nationFlagMd,
  nationFlagMe,
  nationFlagMf,
  nationFlagMg,
  nationFlagMh,
  nationFlagMk,
  nationFlagMl,
  nationFlagMm,
  nationFlagMn,
  nationFlagMo,
  nationFlagMp,
  nationFlagMq,
  nationFlagMr,
  nationFlagMs,
  nationFlagMt,
  nationFlagMu,
  nationFlagMv,
  nationFlagMw,
  nationFlagMx,
  nationFlagMy,
  nationFlagMz,
  nationFlagNa,
  nationFlagNc,
  nationFlagNe,
  nationFlagNf,
  nationFlagNg,
  nationFlagNi,
  nationFlagNl,
  nationFlagNo,
  nationFlagNp,
  nationFlagNr,
  nationFlagNu,
  nationFlagNz,
  nationFlagOm,
  nationFlagPa,
  nationFlagPe,
  nationFlagPf,
  nationFlagPg,
  nationFlagPh,
  nationFlagPk,
  nationFlagPl,
  nationFlagPm,
  nationFlagPn,
  nationFlagPr,
  nationFlagPs,
  nationFlagPt,
  nationFlagPw,
  nationFlagPy,
  nationFlagQa,
  nationFlagRe,
  nationFlagRo,
  nationFlagRs,
  nationFlagRu,
  nationFlagRw,
  nationFlagSa,
  nationFlagSb,
  nationFlagSc,
  nationFlagSd,
  nationFlagSe,
  nationFlagSg,
  nationFlagSh,
  nationFlagSi,
  nationFlagSj,
  nationFlagSk,
  nationFlagSl,
  nationFlagSm,
  nationFlagSn,
  nationFlagSo,
  nationFlagSr,
  nationFlagSs,
  nationFlagSt,
  nationFlagSv,
  nationFlagSx,
  nationFlagSy,
  nationFlagSz,
  nationFlagTa,
  nationFlagTc,
  nationFlagTd,
  nationFlagTf,
  nationFlagTg,
  nationFlagTh,
  nationFlagTj,
  nationFlagTk,
  nationFlagTl,
  nationFlagTm,
  nationFlagTn,
  nationFlagTo,
  nationFlagTr,
  nationFlagTt,
  nationFlagTv,
  nationFlagTw,
  nationFlagTz,
  nationFlagUa,
  nationFlagUg,
  nationFlagUm,
  nationFlagUn,
  nationFlagUs,
  nationFlagUy,
  nationFlagUz,
  nationFlagVa,
  nationFlagVc,
  nationFlagVe,
  nationFlagVg,
  nationFlagVi,
  nationFlagVn,
  nationFlagVu,
  nationFlagWf,
  nationFlagWs,
  nationFlagXk,
  nationFlagYe,
  nationFlagYt,
  nationFlagZa,
  nationFlagZm,
  nationFlagZw
];
